name: blogify
description: "A Blog App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  app_links:
  cached_network_image: 
  cupertino_icons: 
  dartz: 
  dotted_border: 
  equatable: 
  flutter:
    sdk: flutter
  flutter_bloc: 
  get_it: ^7.7.0
  hive: 
  image_picker: 
  internet_connection_checker_plus: 
  intl: 
  path_provider: 
  supabase_flutter: 
  uuid: 

dev_dependencies:
  flutter_lints: 
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/Designer.JPG
