name: blogify
description: "A Blog App"
publish_to: "none" 


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  app_links: ^6.2.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  supabase_flutter: ^2.6.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true